#!/bin/bash
#
# clean build
#
set -e

make clean
make
make test
make deb
sudo rm -f /var/tmp/vdj-player-id
sudo make uninstall ||:
sudo make install
sudo make uninstall
sudo dpkg -i target/*.deb

rm -f /var/tmp/vdj-player-id 
